### ISSUE TITLE
Webkit unable to load polymer-cookie.

### ISSUE THREAD

**Issue by hickscorp** [andreasonny83/polymer-cookie#3]
Hello,

The latest tagged version of polymer-cookie has a function named `readCookie()` declared in a way that Webkit would be unable to parse it.

For now, we are referencing `polymer-cookie` with the latest working commit SHA (a7ad835ccbcb3f0c3330bf3911942ba8a204d83e), but we would really love to see a new version tag instead.

Thanks!

**Comment by GeoloeG-IsT** [comment]
master is also bugged...

https://github.com/andreasonny83/polymer-cookie/pull/4

**Comment by andreasonny83** [comment]
Thanks a lot for your feedback @hickscorp , I just release a new tagged version. I also implemented new features in there.
Let me know if that works so I can close this issue.

Regards
